version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot*"
          - "io.spring.dependency-management*"
          - "gradle-wrapper"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
